### ISSUE TITLE
Postawić VPN

### ISSUE THREAD

**Issue by Ph0enixKM** [ksiuwr/projekt_drzwi_otwarte#23]
Zanim cokolwiek zrobimy - fajnie by było postawić VPN na serwerze KSI. Najlepiej by było stworzyć Ansible playbook, by ten proces w jakiś sposób zautomatyzować. Pytanie czy będziemy go przechowywać na tym repozytorium czy robimy nowe repo _ksi_vpn_?

**Comment by Bozydarek** [comment]
Jako, że sam VPN nie będzie postawiony na Raspie, ani jego konfiguracja będzie częścią tego projektu proponowałbym raczej utworzenie osobnego repozytorium gdzie znajdzie się pełna konfiguracja serwera (także dla przyszłych projektów) - np. _ksi-server-configuration_. Warto pamiętać o dobrym zadbaniu o sekrety, w szczególności, że wszystkie repozytoria koła są publiczne ;)
